import customtkinter as ctk

TRANSLATIONS = {
    "AR": {
        "title": "AutoForge AI",
        "subtitle": "⚡ نظام النشر الذكي المتقدم وأتمتة البيئات البرمجية",
        "author": "⚡ ARCHITECT: YASSINE DELLA ⚡",
        "placeholder": "اكتب طلبك باللغة الطبيعية (مثال: جهز برامج السمعيات والتصفح)...",
        "filter_placeholder": "🔍 تصفية سريعة بالاسم أو التصنيف...",
        "ask_ai": "⚡ تحليل واستخراج الحزم عبر الذكاء الاصطناعي",
        "select_uninstalled": "غير المثبتة",
        "select_all": "تحديد الكل",
        "deselect_all": "إلغاء التحديد",
        "refresh": "🔄 تحديث",
        "settings": "⚙️ الإعدادات",
        "export_log": "📋 تصدير السجل",
        "add_custom": "📁 إضافة ملفات/مجلد",
        "frame_title": "الحزم والمجلدات المكتشفة",
        "total_count": "إجمالي البرامج: {count} حزمة",
        "installed_tag": "(مثبت: {ver})",
        "btn_install": "▶ تشغيل خطة التثبيت الصامت الفوري",
        "btn_stop": "⏹ إيقاف فوري للعملية",
        "time_status": "المنقضي: {elapsed} | المتبقي التقديري: {eta}",
        "empty_apps": "لا توجد برامج مطابقة داخل المجلدات المحددة!",
        "status_waiting": "في الانتظار...",
        "status_installing": "⏳ جاري التثبيت...",
        "status_success": "✓ تم بنجاح",
        "status_failed": "✗ فشل / خطأ",
        "status_skipped": "⊘ تم التخطي",
        "system_ready": "[AI Core] المحرك العصبي جاهز وبانتظار الأوامر يا ياسين...\n",
        "finish_msg": "--- [FINISH] اكتملت كافة عمليات التثبيت بنجاح تام يا ياسين! ---",
        "preset_all": "الكل",
        "preset_audio": "🦻 السمعيات",
        "preset_drivers": "🔌 التعريفات",
        "preset_runtimes": "⚙️ المكتبات",
        "preset_browsers": "🌐 المتصفحات",
        "category_all": "جميع الفئات"
    },
    "FR": {
        "title": "AutoForge AI",
        "subtitle": "⚡ Système Intelligent de Déploiement et d'Automatisation",
        "author": "⚡ ARCHITECT: YASSINE DELLA ⚡",
        "placeholder": "Tapez votre demande (ex: logiciels audio et navigateurs)...",
        "filter_placeholder": "🔍 Filtrer par nom ou catégorie...",
        "ask_ai": "⚡ Analyse et Sélection par IA",
        "select_uninstalled": "Non Installés",
        "select_all": "Tout Cocher",
        "deselect_all": "Tout Décocher",
        "refresh": "🔄 Actualiser",
        "settings": "⚙️ Paramètres",
        "export_log": "📋 Exporter Journal",
        "add_custom": "📁 Ajouter Fichiers/Dossier",
        "frame_title": "Packages et Dossiers Détectés",
        "total_count": "Total programmes: {count} paquets",
        "installed_tag": "(Installé: {ver})",
        "btn_install": "▶ Lancer l'Installation Silencieuse",
        "btn_stop": "⏹ Arrêt Immédiat",
        "time_status": "Écoulé: {elapsed} | Restant estimé: {eta}",
        "empty_apps": "Aucun programme correspondant trouvé!",
        "status_waiting": "En attente...",
        "status_installing": "⏳ En cours...",
        "status_success": "✓ Installé",
        "status_failed": "✗ Échec",
        "status_skipped": "⊘ Ignoré",
        "system_ready": "[AI Core] Moteur neuronal prêt, en attente de commandes Yassine...\n",
        "finish_msg": "--- [FINISH] Installations terminées avec succès Yassine! ---",
        "preset_all": "Tous",
        "preset_audio": "🦻 Audio",
        "preset_drivers": "🔌 Pilotes",
        "preset_runtimes": "⚙️ Runtimes",
        "preset_browsers": "🌐 Web",
        "category_all": "Toutes Catégories"
    }
}
